// Bakes the icon files into a TypeScript source file.
//
// The installer has to write a .ico on Windows and PNGs on Linux, and gitc
// ships as one binary with no files beside it - so the bytes have to travel
// inside it.
//
// They are embedded as base64 text rather than byte arrays: text compiles
// quickly and stays readable in a diff as one line, and the engine decodes it
// with a few lines of arithmetic (see engine/base64.ts) rather than relying on
// a runtime decoder.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const icons = join(root, "icons");
const outFile = join(root, "src", "generated", "icons.ts");

/** The .ico is for Windows shortcuts; the PNGs for the Linux icon theme. */
const PNG_SIZES = [16, 24, 32, 48, 64, 128, 256];

function b64(path) {
  if (!existsSync(path)) {
    console.error(`missing ${path} - run: node scripts/make-icons.mjs`);
    process.exit(1);
  }
  return readFileSync(path).toString("base64");
}

const parts = [];
parts.push(`export const ICO_BASE64 = ${JSON.stringify(b64(join(icons, "gitc.ico")))};`);
parts.push("");
parts.push("/** PNG icons by pixel size, for the Linux hicolor theme. */");
parts.push("export const PNG_BASE64: { size: number; data: string }[] = [");
for (const size of PNG_SIZES) {
  parts.push(`  { size: ${size}, data: ${JSON.stringify(b64(join(icons, `gitc-${size}.png`)))} },`);
}
parts.push("];");

const source = `// GENERATED by scripts/embed-icons.mjs from icons/ - do not edit.

${parts.join("\n")}
`;

const dir = dirname(outFile);
if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
writeFileSync(outFile, source, "utf8");

const kb = (source.length / 1024).toFixed(0);
console.log(`embedded ${PNG_SIZES.length + 1} icon files (${kb} KB) -> src/generated/icons.ts`);
