// Bakes the built UI into a TypeScript source file so scriptc can compile it
// into the binary. gitc ships as one file with no asset directory beside it.
//
// The output is a switch rather than a record: it is the shape most certain
// to lower cleanly, and it keeps the "unknown asset" case explicit.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const built = join(root, "build", "ui");
const outDir = join(root, "src", "generated");
const outFile = join(outDir, "assets.ts");

const FILES = ["index.html", "app.js", "app.css"];

if (!existsSync(built)) {
  console.error("build/ui missing - run: npm run build:ui");
  process.exit(1);
}

const parts = [];
let total = 0;

for (const name of FILES) {
  const path = join(built, name);
  if (!existsSync(path)) {
    console.error(`expected ${name} in build/ui`);
    process.exit(1);
  }
  const body = readFileSync(path, "utf8");
  total += Buffer.byteLength(body, "utf8");
  // JSON.stringify gives a correctly escaped TS string literal, including
  // the newlines and quotes that a bundled app is full of.
  parts.push(`  if (name === ${JSON.stringify(name)}) return ${JSON.stringify(body)};`);
}

const source = `// GENERATED by scripts/embed.mjs - do not edit.
// Source: build/ui, produced by \`vite build\`.

/** Returns a baked UI asset, or null when the name is unknown. */
export function bakedAsset(name: string): string | null {
${parts.join("\n")}
  return null;
}
`;

if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, source, "utf8");

console.log(
  `embedded ${FILES.length} assets (${(total / 1024).toFixed(1)} KB) -> src/generated/assets.ts`,
);
