// Propagates the version from package.json into the source tree.
//
// package.json is the single source of truth. Nothing else states the version:
// the status bar, `gitc --version` and the release tag all read the generated
// file this writes, so bumping one number is the whole job.
//
// The file is generated rather than imported because the engine compiles to a
// binary that does not ship package.json, and Vite's `define` would only cover
// the UI half.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

const out = join(root, "src", "generated", "version.ts");
// The updater asks GitHub about this repository, and package.json already
// says which one it is - so it is not spelled out a second time.
const url = (pkg.repository && pkg.repository.url) || "";
const match = url.match(/github\.com[:/]+([^/]+\/[^/.]+)/);
const repo = match ? match[1] : "";

const body = `// Generated by scripts/version.mjs from package.json - do not edit.
export const VERSION = ${JSON.stringify(pkg.version)};
export const NAME = ${JSON.stringify(pkg.name)};
/** owner/name on GitHub, for the updater. Empty when there is no remote. */
export const REPO = ${JSON.stringify(repo)};
`;

const dir = dirname(out);
if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

// Only write when it changed, so a dev server watching the tree does not
// reload on every invocation.
const current = existsSync(out) ? readFileSync(out, "utf8") : "";
if (current !== body) {
  writeFileSync(out, body, "utf8");
  console.log(`version ${pkg.version} -> src/generated/version.ts`);
}
